src/Entity/Document.php
<?php

namespace App\Entity;

use App\Repository\DocumentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=DocumentRepository::class)
 */
class Document
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $file_document;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $detail;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="documents")
     */
    private $user;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getFileDocument(): ?string
    {
        return $this->file_document;
    }

    public function setFileDocument(string $file_document): self
    {
        $this->file_document = $file_document;

        return $this;
    }

    public function getDetail(): ?string
    {
        return $this->detail;
    }

    public function setDetail(?string $detail): self
    {
        $this->detail = $detail;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/DocumentType.php
<?php

namespace App\Form;

use App\Entity\Document;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;

class DocumentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titre' , TextType::class)
            ->add('file_document' ,  FileType::class, [
                'label' => 'Joindre le fichier',

                // unmapped means that this field is not associated to any entity property
                'mapped' => false,

                // make it optional so you don't have to re-upload the PDF file
                // every time you edit the Product details
                'required' => false,

                // unmapped fields can't define their validation using annotations
                // in the associated entity, so you can use the PHP constraint classes
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'application/pdf',
                            'application/x-pdf',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid PDF document',
                    ])
                ]
                ])
                
            ->add('detail' , TextareaType::class , [
                "label"=>"description"
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Document::class,
        ]);
    }
}

src/Controller/admin/DocumentController.php
<?php

namespace App\Controller;

use App\Entity\Document;
use App\Form\DocumentType;
use App\Repository\DocumentRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Service\FileUploader;
/**
 * @Route("/document")
 */
class DocumentController extends AbstractController
{
    /**
     * @Route("/", name="app_document_index", methods={"GET"})
     */
    public function index(DocumentRepository $documentRepository): Response
    {
        return $this->render('document/index.html.twig', [
            'documents' => $documentRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_document_new", methods={"GET", "POST"})
     */
    public function new(FileUploader $fileUploader , Request $request, DocumentRepository $documentRepository): Response
    {
        $document = new Document();
        $form = $this->createForm(DocumentType::class, $document);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) 
        {
            $brochureFile = $form->get('file_document')->getData();
            if ($brochureFile) {
                $brochureFileName = $fileUploader->upload($brochureFile);
                $document->setFileDocument($brochureFileName);
                $documentRepository->add($document);
                return $this->redirectToRoute('app_document_index', [], Response::HTTP_SEE_OTHER);
            }
        }
        return $this->renderForm('document/new.html.twig', [
            'document' => $document,
            'form' => $form,
            ]);
    }

    /**
     * @Route("/{id}", name="app_document_show", methods={"GET"})
     */
    public function show(Document $document): Response
    {
        return $this->render('document/show.html.twig', [
            'document' => $document,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_document_edit", methods={"GET", "POST"})
     */
    public function edit(FileUploader $fileUploader , Request $request, Document $document, DocumentRepository $documentRepository): Response
    {
        $form = $this->createForm(DocumentType::class, $document);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) 
        {
            $brochureFile = $form->get('file_document')->getData();
            if ($brochureFile) {
                $brochureFileName = $fileUploader->upload($brochureFile);
                $document->setFileDocument($brochureFileName);
                $documentRepository->add($document);
                return $this->redirectToRoute('app_document_index', [], Response::HTTP_SEE_OTHER);
            }
        }

        return $this->renderForm('document/edit.html.twig', [
            'document' => $document,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_document_delete", methods={"POST"})
     */
    public function delete(Request $request, Document $document, DocumentRepository $documentRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$document->getId(), $request->request->get('_token'))) {
            $documentRepository->remove($document);
        }

        return $this->redirectToRoute('app_document_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/document/_delete_form.html.twig
<form method="post" action="{{ path('app_document_delete', {'id': document.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ document.id) }}">
    <button class="btn">Delete</button>
</form>

templates/document/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-success">{{ button_label|default('Enregister ') }}</button>
{{ form_end(form) }}

templates/document/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Document{% endblock %}

{% block body %}
    <h1>Edit Document</h1>

    {{ include('document/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_document_index') }}">back to list</a>

    {{ include('document/_delete_form.html.twig') }}
{% endblock %}

templates/document/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Document index{% endblock %}

{% block body %}
    <h1>Document index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>File_document</th>
                <th>Detail</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for document in documents %}
            <tr>
                <td>{{ document.id }}</td>
                <td>{{ document.titre }}</td>
                <td>{{ document.fileDocument }}</td>
                <td>{{ document.detail }}</td>
                <td>
                    <a href="{{ path('app_document_show', {'id': document.id}) }}">show</a>
                    <a href="{{ path('app_document_edit', {'id': document.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_document_new') }}">Create new</a>
{% endblock %}

templates/document/new.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div class="wrapper">
  <div class="content-wrapper">
        <div class="row" style="padding-left:2%;padding-top:2%">
          <div class="col-md-8">
            <div class="card card-success">
              <div class="card-header">
               <strong> Gestion document  </strong>
               
              </div>
              <!-- /.card-header -->
              <div class="card-body">
                 {{ include('document/_form.html.twig') }}
             </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/document/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Document{% endblock %}

{% block body %}
    <h1>Document</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ document.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ document.titre }}</td>
            </tr>
            <tr>
                <th>File_document</th>
                <td>{{ document.fileDocument }}</td>
            </tr>
            <tr>
                <th>Detail</th>
                <td>{{ document.detail }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_document_index') }}">back to list</a>

    <a href="{{ path('app_document_edit', {'id': document.id}) }}">edit</a>

    {{ include('document/_delete_form.html.twig') }}
{% endblock %}