src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use DoctrineExtensions\Query\Mysql\Date;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Security\Core\Validator\Constraints as SecurityAssert;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="Votre compte existe dejà")
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     * @Assert\NotBlank
     * @Assert\Email(message = "The email '{{ value }}' is not a valid email"
     * )
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @Assert\Length(min = 6, max = 12, minMessage = "votre mot de passe doit avoir 6 caractere min ", maxMessage = "votre mot de passe doit avoir ne doit pas depasser  caractere 12 caracteres ")
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

  

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank
     */
    private $Nom;

    /**
     * @ORM\OneToMany(targetEntity=Etudiant::class, mappedBy="user")
     */
    private $etudiants;

    

    /**
     * @ORM\OneToMany(targetEntity=ParcoursUniversitaire::class, mappedBy="user")
     */
    private $parcoursUniversitaires;

    /**
     * @ORM\OneToMany(targetEntity=Langue::class, mappedBy="user")
     */
    private $langues;

    /**
     * @ORM\OneToMany(targetEntity=Experience::class, mappedBy="user")
     */
    private $experiences;

    /**
     * @ORM\OneToMany(targetEntity=Responsable::class, mappedBy="user")
     */
    private $responsables;

       /**
     * @ORM\OneToMany(targetEntity=Flux::class, mappedBy="user")
     */
    private $fluxes;
    
    /**
     * @ORM\OneToMany(targetEntity=Bourse::class, mappedBy="user")
     */
    private $bourses;
    

    /**
     * @ORM\OneToMany(targetEntity=FluxSortant::class, mappedBy="user")
     */
    private $fluxSortants;

    /**
     * @ORM\OneToMany(targetEntity=Candidature::class, mappedBy="user")
     */
    private $candidatures;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    

    /**
     * @ORM\Column(type="float")
     * @Assert\Positive
     * @Assert\NotBlank
     * @Assert\Length(
     *      min = 1,
     *      max = 5,
     *      minMessage = "Your first name must be at least {{ limit }} characters long",
     *      maxMessage = "Your first name cannot be longer than {{ limit }} characters"
     * )
     */
    private $Numerocarte;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nin;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $session;

    /**
     * @ORM\OneToMany(targetEntity=Diplome::class, mappedBy="user")
     */
    private $diplomes;

    /**
     * @ORM\OneToMany(targetEntity=InformationBac::class, mappedBy="user")
     */
    private $informationBacs;

    /**
     * @ORM\OneToMany(targetEntity=Document::class, mappedBy="user")
     */
    private $documents;

    /**
     * @ORM\OneToMany(targetEntity=Authentification::class, mappedBy="user")
     */
    private $authentifications;

    /**
     * @ORM\OneToMany(targetEntity=Droit::class, mappedBy="user")
     */
    private $droits;

    
public function __construct()
    {
        $this->etudiants = new ArrayCollection();
       
        $this->parcoursUniversitaires = new ArrayCollection();
        $this->langues = new ArrayCollection();
        $this->experiences = new ArrayCollection();
        $this->responsables = new ArrayCollection();
        $this->bourses = new ArrayCollection();
      
        $this->fluxes = new ArrayCollection();
        $this->fluxSortants = new ArrayCollection();
        
        $this->candidatures = new ArrayCollection();
        $this->diplomes = new ArrayCollection();
        $this->informationBacs = new ArrayCollection();
       
        $this->users = new ArrayCollection();
        $this->documents = new ArrayCollection();
        $this->authentifications = new ArrayCollection();
        $this->droits = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    /**
     * @return Collection|Etudiant[]
     */
    public function getEtudiants(): Collection
    {
        return $this->etudiants;
    }

    public function addEtudiant(Etudiant $etudiant): self
    {
        if (!$this->etudiants->contains($etudiant)) {
            $this->etudiants[] = $etudiant;
            $etudiant->setUser($this);
        }

        return $this;
    }

    public function removeEtudiant(Etudiant $etudiant): self
    {
        if ($this->etudiants->removeElement($etudiant)) {
            // set the owning side to null (unless already changed)
            if ($etudiant->getUser() === $this) {
                $etudiant->setUser(null);
            }
        }

        return $this;
    }

   

    /**
     * @return Collection|ParcoursUniversitaire[]
     */
    public function getparcours_universitaires(): Collection
    {
        return $this->parcoursUniversitaires;
    }

    public function addParcoursUniversitaire(ParcoursUniversitaire $parcoursUniversitaire): self
    {
        if (!$this->parcoursUniversitaires->contains($parcoursUniversitaire)) {
            $this->parcoursUniversitaires[] = $parcoursUniversitaire;
            $parcoursUniversitaire->setUser($this);
        }

        return $this;
    }

    public function removeParcoursUniversitaire(ParcoursUniversitaire $parcoursUniversitaire): self
    {
        if ($this->parcoursUniversitaires->removeElement($parcoursUniversitaire)) {
            // set the owning side to null (unless already changed)
            if ($parcoursUniversitaire->getUser() === $this) {
                $parcoursUniversitaire->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Langue[]
     */
    public function getLangues(): Collection
    {
        return $this->langues;
    }

    public function addLangue(Langue $langue): self
    {
        if (!$this->langues->contains($langue)) {
            $this->langues[] = $langue;
            $langue->setUser($this);
        }

        return $this;
    }

    public function removeLangue(Langue $langue): self
    {
        if ($this->langues->removeElement($langue)) {
            // set the owning side to null (unless already changed)
            if ($langue->getUser() === $this) {
                $langue->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Experience[]
     */
    public function getExperiences(): Collection
    {
        return $this->experiences;
    }

    public function addExperience(Experience $experience): self
    {
        if (!$this->experiences->contains($experience)) {
            $this->experiences[] = $experience;
            $experience->setUser($this);
        }

        return $this;
    }

    public function removeExperience(Experience $experience): self
    {

src/Controller/EtudiantController.php
<?php

namespace App\Controller;


use App\Entity\Etudiant;
use App\Service\FileUploader;
use App\Form\EtudiantType;
use App\Form\User;
use App\Repository\EtudiantRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\String\Slugger\SluggerInterface;
/**
 * @Route("/etudiant")
 */
class EtudiantController extends AbstractController
{
    //je declare la variable repo pour recupere la repository 
    private $repo;
    //je declare le constructeur de cette classe 
    public function __construct(EtudiantRepository $repo){
        $this->repo = $repo ;
    }
   

    
    
    /**
     * @Route("/", name="etudiant_index", methods={"GET"})
     */
    public function index(EtudiantRepository $etudiantRepository): Response
    {
        return $this->render('etudiant/index.html.twig', [
            'etudiants' => $etudiantRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="etudiant_new", methods={"GET","POST"})
     */
    public function new(FileUploader $fileUploader , Request $request , EtudiantRepository $etudiantRepository): Response
    {
        $etudiant = new Etudiant();
        $serie = NULL;
        $etudiant->setUser($this->getUser());
       // $etudiant->setCodeDoosier("2022KKLE");
        
        $form = $this->createForm(EtudiantType::class, $etudiant);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            $brochureFile1 = $form->get('photo')->getData();
            $brochureFile2 = $form->get('Pieceidentite')->getData();
           
            
            // this condition is needed because the 'brochure' field is not required
            // so the PDF file must be processed only when a file is uploaded
           
            if ($brochureFile1 || $brochureFile2) {
                $brochureFileName1 = $fileUploader->upload($brochureFile1);
                $brochureFileName2 = $fileUploader->upload($brochureFile2);
               

                $etudiant->setPieceidentite($brochureFileName2);
                $etudiant->setPhoto($brochureFileName1);
               
            }
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($etudiant);
            $entityManager->flush();
            $this->addFlash("success" , "informations personnelles  sont bien enregistrées avec success ");

            return $this->redirectToRoute('home_accueil', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('etudiant/new.html.twig', [
            'etudiant' => $etudiant,
            'form' => $form , 
            "serie"=>  $serie , 
            'etudiants' => $etudiantRepository->findAll(),
            
        ]);
    }

    /**
     * @Route("/{id}", name="etudiant_show", methods={"GET"})
     */
    public function show(Etudiant $etudiant): Response
    {
        return $this->render('etudiant/show.html.twig', [
            'etudiant' => $etudiant,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="etudiant_edit", methods={"GET","POST"})
     */
    public function edit(FileUploader $fileUploader ,Request $request, Etudiant $etudiant): Response
    {
        $form = $this->createForm(EtudiantType::class, $etudiant);
        $form->handleRequest($request);
   
        if ($form->isSubmitted() && $form->isValid()) {
            $brochureFile1 = $form->get('photo')->getData();
            $brochureFile2 = $form->get('Pieceidentite')->getData();
          
            
            // this condition is needed because the 'brochure' field is not required
            // so the PDF file must be processed only when a file is uploaded
           
            if ($brochureFile1 || $brochureFile2 ) {
                $brochureFileName1 = $fileUploader->upload($brochureFile1);
                $brochureFileName2 = $fileUploader->upload($brochureFile2);
               

                $etudiant->setPieceidentite($brochureFileName2);
                $etudiant->setPhoto($brochureFileName1);
               
            }
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('home_accueil', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('etudiant/edit.html.twig', [
            'etudiant' => $etudiant,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="etudiant_delete", methods={"POST"})
     */
    public function delete(Request $request, Etudiant $etudiant): Response
    {
        if ($this->isCsrfTokenValid('delete'.$etudiant->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($etudiant);
            $entityManager->flush();
        }

        return $this->redirectToRoute('home_accueil', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * @Route("/reca", name="etudiant_reca", methods={"GET"})
     * @ParamConverter("etudiant" , class="App\Repository\EtudiantRepository")
     */
    public function recap(EtudiantRepository $etudiant): Response
    {
          return $this->render('recap.html.twig',[
              'etudiant'=>$etudiant->findAll()
         ]);
     }
}

templates/etudiant/_delete_form.html.twig
<form method="post" action="{{ path('etudiant_delete', {'id': etudiant.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ etudiant.id) }}">
       <button class="btn btn-danger btn-md">suprimer</button>
</form>

templates/etudiant/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
  <div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-sm-6">
            <h1 class="m-0">Dashboard</h1>
          </div><!-- /.col -->
          <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="#">Home</a></li>
              <li class="breadcrumb-item active">Dashboard v1</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <section class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="col-md-12">
            <div class="card card-primary card-outline">
              <div class="card-header">
                <h3 class="card-title">
                  <i class="fas fa-edit"></i>
                  Modal Examples
                </h3>
              </div>
              <div class="card-body">
                  <div class="col-md-6">
                    <table id="todo" class="table table-bordered">
                    
                      <tbody style="padding-top:3%">
                      {% for etudiant in app.user.etudiants  %}
                      <tr>
                        <td>
                        Email: {{ app.user.email  }} 
                      </td>
                      <td>
                        Nom: {{ app.user.nom  }} 
                      </td>
                      <td>
                        Prenom: {{ app.user.prenom }} 
                      </td>
                      </tr>
                        {% endfor %}
                       
                        <tr>
                          <td>
                          
                        </td>
                        </tr>
                        {% for etudiant in app.user.etudiants  %}
                        <tr>
                          <td>
                          Lieu de Naissance  : {{ etudiant.lieuNaissance  }} 
                        </td>
                        </tr>
                        <tr>
                          <td>
                        Date de naissance: {{ etudiant.dateNaissance ? etudiant.dateNaissance|date('Y-m-d') : '' }}
                        </td>
                        </tr>
                        <tr>
                            <td>
                            Adresse : {{ etudiant.adresse  }}
                            </td>
                        </tr>
                        <tr>
                            <td>
                            Ile: {{ etudiant.ile  }}
                            </td>
                        </tr>
                      
                        <tr>
                            <td>
                        Sexe : {{ etudiant.sexe   }}
                            </td>
                        </tr>
                        <tr>
                            <td>
                            Actions : 
                            <button type="button" class="btn btn-theme04 delete">
                          <a href="{{ path('etudiant_show', {'id': etudiant.id}) }}"> <i class="glyphicon glyphicon-trash"></i></a>
                            <span>Delete</span>
                        </button>

                          <a href="{{ path('etudiant_edit', {'id': etudiant.id}) }}">
                          <button type="button" class="btn btn-theme start">
                            <i class="glyphicon glyphicon-pencil"></i>
                            <span>Editer</span>
                        </button> 
                            </td>
                        </tr>
                        
                      </tbody>
                      
                      {% endfor %}
                    
                    </table>
                  </div>
                <div   class="col-md-6">
                 <table id="todo" class="table table-hover table-bordered">
                 {% for etudiant in app.user.etudiants %}
                  <tbody>
                    <tr>
                      <td>
                        Nationalité : {{ etudiant.nationalite  }} 
                    </td>
                    </tr>
                    <tr>
                      <td>
                       Type de piece d'identité : {{ etudiant.typeIdentite   }} 
                    </td>
                    </tr>
                   
                    <tr>
                      <td>
                     N° de piece d'identité : {{ app.user.nin }}
                    </td>
                    </tr>
                    
                    </tr>
                    <tr>
                        <td>
                        Actions : 
                        <button type="button" class="btn btn-theme04 delete">
                       <a href="{{ path('etudiant_show', {'id': etudiant.id}) }}"> <i class="glyphicon glyphicon-trash"></i></a>
                        <span>Delete</span>
                     </button>

                      <a href="{{ path('etudiant_edit', {'id': etudiant.id}) }}">
                      <button type="button" class="btn btn-theme start">
                        <i class="glyphicon glyphicon-pencil"></i>
                        <span>Editer</span>
                     </button>
                     </a>
                    </td>
                    </tr>
                  </tbody>
                
                  {% endfor %}
                </table>
                </div>
                </div>
                <!-- /.card -->
              </div>
            
          </div>
       
        <!-- /row -->
      </section>
      <!-- /wrapper -->
</section>
    <!-- /.content -->
  </div>
{% endblock %}

templates/etudiant/new.html.twig
{% include 'link/nav.html.twig' %}
{% include 'link/link_css.html.twig' %}
  
{% block body %}
    <div class="wrapper" style="padding-left:12%">
        <div class="content-wrapper">
            <div class="row" style="padding-top:10%">
                {% if (app.user.etudiants | length) < 1  %}
                    <div class="col-md-10">
                        <div class="card card-success">
                            <div class="card-header">
                            <strong> Information personnelles  </strong>
                            </div>  
                            <div class="card-body">
                                {{ include('etudiant/_form.html.twig') }}
                                <br>
                            </div>
                        </div>
                        </div>
                        {% else %}
                            <div class="col-md-8">
                                <div class="card">
                                    <div class="card-body">
                                    <h4 class="card-header">  Mes informations personnelles    </h4>  
                                    <div class="table-responsive">
                                    <table class="table table-striped table-bordered" style=" width: 100%">
                                        <tbody>
                                        {% for etudiant in app.user.etudiants %}
                                            <tr>
                                                <th>Genre </th>
                                                <td>{{ etudiant.sexe }}</td>
                                            </tr>
                                            <tr>
                                                <th>Situation familiale et maritale </th>
                                                <td>{{ etudiant.etatcivile }}</td>
                                            </tr>
                                            
                                            <tr>
                                                <th>Nom de famille </th>
                                                <td>{{ app.user.nom }}</td>
                                            </tr>
                                            <tr>
                                                <th>Prenom</th>
                                                <td>{{ app.user.prenom }}</td>
                                            </tr>
                                            <tr>
                                                <th>Adresse E-mail</th>
                                                <td>{{ app.user.email }}</td>
                                            </tr>
                                            <tr>
                                                <th>Numero de telephone</th>
                                                <td>{{ etudiant.telephone }}</td>
                                            </tr>
                                            <tr>
                                                <th>Personne à contacter en cas d'urgence </th>
                                                <td>{{ etudiant.telUrgence }}</td>
                                            </tr>

                                            <tr>
                                                <th>Date de naissance</th>
                                                <td>{{ etudiant.dateNaissance ? etudiant.dateNaissance|date('Y-m-d') : '' }}</td>
                                            </tr>
                                            <tr>
                                                <th>Adresse domicile </th>
                                                <td>{{ etudiant.adresse }}</td>
                                            </tr>
                                            <tr>
                                                <th>Lieu de naissance</th>
                                                <td>{{ etudiant.lieuNaissance }}</td>
                                            </tr>
                                            <tr>
                                                <th>Nin (numero de carte d'identité ) </th>
                                                <td>{{ app.user.nin }}</td>
                                            </tr>
                                        <tr>
                                                <th>Nationalité</th>
                                                <td>{{ etudiant.nationalite }}</td>
                                            </tr>
                                            
                                            <tr>
                                                <th>Ile de naissance  </th>
                                                <td>{{ etudiant.ile }}</td>
                                            </tr>
                                            <tr>
                                                <th>Date de Validité piece d'identité </th>
                                                <td>{{ etudiant.dateExpiration ? etudiant.dateExpiration|date('Y-m-d') : '' }}</td>
                                            </tr>
                                            <tr>
                                                <th>Type de piece d'identite</th>
                                                <td>{{ etudiant.typeIdentite }}</td>
                                            </tr>
                                            <tr>
                                                <th>Pays de delivrance</th>
                                                <td>{{ etudiant.pays }}</td>
                                            </tr>
                                            
                                            <tr>
                                                <th>Date de delivrance </th>
                                                <td>{{ etudiant.dateDelivrance ? etudiant.dateDelivrance|date('Y-m-d') : '' }}</td>
                                            </tr>
                                            <tr>
                                                <th>Numero de carte d'identité  </th>
                                                <td>{{ etudiant.NumCarteidentite }}</td>
                                            </tr>
                                            
                                            <tr>
                                                <th> Piece d'identité   </th>
                                                <td> <a href="{{ asset('uploads/'~ etudiant.Pieceidentite) }}">consulter </a></td>
                                            </tr>
                                            <tr>
                                            {% for candidat in app.user.candidatures %}
                                                {% if candidat.status == 0  %}
                                                    <th>Actions  </th>
                                                    <td>
                                                        <a class="btn btn-success" href="{{ path('etudiant_edit', {'id': etudiant.id}) }}"> editer</a>
                                                        <div style="display:inline-block">   {{ include('etudiant/_delete_form.html.twig') }} </div>
                                                        <a class="btn btn-primary"  href="{{ path('responsable_new')}}"> <i class="fa fa-location-arrow" aria-hidden="true"></i>
                                                        Passer à l'etape suivante 
                                                        </a>
                                                        <br>
                                                        <br>
                                                        
                                                    </td>
                                                    {% else %}
                                                    
                                                {% endif %}
                                            {% endfor %}
                                            
                                            </tr>
                                            {% endfor %}
                                        </tbody>
                                        
                                    </table>
                                    <br>
                                    
                                    
                                    {% for msg in app.flashes('success') %}
                                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                            </button>
                                            <strong>  {{msg }} </strong> 
                                        </div>
                                        <script>
                                        $(".alert").alert();
                                        </script>
                                            
                                        </div>
                                    {% endfor %}
                                </div>
                                </div>
                            </div>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
  {{ include('link/footer.html.twig') }}   
{% endblock %}


      
          